project:
  type: website
  output-dir: docs

website:
  title: "2023 Workshop: Charting human biology using AI for Precision Health & Precision Medicine"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/crazyhottommy/charting_human_biology_using_AI
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: materials.qmd
        text: Materials
      - href: https://github.com/crazyhottommy/charting_human_biology_using_AI/discussions
        text: Forum

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

